calidad_minima=60
sid4k0703=S
barcodeSaturation=S
secugen_security_level=2
threshold=10
thresholdCC=15
apagarautomaticamentecamara=S
rutaimg=R:\\PruebasCajaMS\\
nombreImg=image.jpg
rutaimg1=R:\\PruebasCajaMS\\
cantMsjVerfHuellaDocViva=2
guardarimagenlogi=N
